Add check for valid or invalid semver version

diff --git a/.github/workflows/bump-version.yml b/.github/workflows/bump-version.yml
--- a/.github/workflows/bump-version.yml
+++ b/.github/workflows/bump-version.yml
@@ -22,9 +22,17 @@ jobs:
           else
             echo "feature_flag=0" >> $GITHUB_ENV
           fi
-      - name: Get current version from composer.json
+      - name: Get current version from ${{ env.versioned_file }}
         run: |
-          echo "current_version=$(grep -m1 version composer.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')" >> $GITHUB_ENV
+          echo "current_version=$(grep -m1 version ${{ env.versioned_file }} | awk -F: '{ print $2 }' | sed 's/[", ]//g')" >> $GITHUB_ENV
+      - name: Fail if version is invalid
+        run: |
+          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "valid semver version"
+          else
+            echo "::error Invalid semver version: $version"
+            exit 1
+          fi
       - name: Bump Minor Version
         if: ${{ env.feature_flag == '1' }}
         run: |
